name: Pull Request

on: pull_request

jobs:
  lint:
    name: Lint on node 20 and ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
      - name: Lint codebase
        run: yarn lint
  test:
    name: Test and lint on node 20.x and ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
      - name: Test codebase
        run: yarn test
      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)
